name: CICD for NestoHub

on:
  push:
    branches:
        - main

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ubuntu
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
               sudo su ubuntu
               cd ..
               cd ..
               cd Nesto-Frontend/
               git pull origin main
               pm2 restart web
