name: CICD for NestoHub

on:
  push:
    branches:
        - main

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ubuntu
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh
               nvm install 16.14.0
               npm install -g pm2
               cd ..
               cd ..
               cd Nesto-Frontend/
               git pull origin main
               pm2 restart web
